// frontend/src/app/shared/cv-preview/cv-preview.component.ts
import { Component, Input, inject } from '@angular/core';

import { CVStructure } from '../../services/cv.service';
import { I18nService } from '../../services/i18n.service';

/**
 * Renders a CVStructure as a clean, A4-style single-page document. Used by the
 * CV editor's "Preview" tab for a live, WYSIWYG look at the resume.
 */
@Component({
  selector: 'app-cv-preview',
  standalone: true,
  template: `
    <div class="cv-preview-sheet">
      <header class="cv-head">
        <h2>{{ name }}</h2>
        <p class="cv-contact">
          @if (cv.summary) {
            <span>{{ cv.summary }}</span>
          } @else {
            <span class="empty">{{ i18n.t('cvPreview.summaryEmpty') }}</span>
          }
        </p>
      </header>

      @if (cv.skills.length > 0) {
        <section class="cv-section">
          <h3>{{ i18n.t('cvPreview.skills') }}</h3>
          <div class="cv-skills">
            @for (skill of cv.skills; track skill) {
              <span class="skill-chip">{{ skill }}</span>
            }
          </div>
        </section>
      }

      @if (cv.experience.length > 0) {
        <section class="cv-section">
          <h3>{{ i18n.t('cvPreview.experience') }}</h3>
          @for (exp of cv.experience; track $index) {
            <div class="cv-entry">
              <div class="cv-entry-head">
                <strong>{{ exp.title }}</strong>
                <span class="cv-dates">{{ formatDates(exp.start_date, exp.end_date) }}</span>
              </div>
              <div class="cv-entry-sub">{{ exp.company }}</div>
              @if (exp.bullets.length > 0) {
                <ul class="cv-bullets">
                  @for (bullet of exp.bullets; track bullet) {
                    <li>{{ bullet }}</li>
                  }
                </ul>
              }
            </div>
          }
        </section>
      }

      @if (cv.education.length > 0) {
        <section class="cv-section">
          <h3>{{ i18n.t('cvPreview.education') }}</h3>
          @for (edu of cv.education; track $index) {
            <div class="cv-entry">
              <div class="cv-entry-head">
                <strong>{{ edu.degree }}</strong>
                <span class="cv-dates">{{ edu.year }}</span>
              </div>
              <div class="cv-entry-sub">{{ edu.institution }}</div>
            </div>
          }
        </section>
      }

      @if (cv.projects.length > 0) {
        <section class="cv-section">
          <h3>{{ i18n.t('cvPreview.projects') }}</h3>
          @for (project of cv.projects; track $index) {
            <div class="cv-entry">
              <div class="cv-entry-head">
                <strong>{{ project.name }}</strong>
                @if (project.link) {
                  <span class="cv-dates">{{ project.link }}</span>
                }
              </div>
              @if (project.description) {
                <p class="cv-desc">{{ project.description }}</p>
              }
            </div>
          }
        </section>
      }
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
        background: var(--color-surface-muted);
        border-radius: var(--radius-lg);
        padding: var(--space-6);
      }

      .cv-preview-sheet {
        max-width: 640px;
        margin: 0 auto;
        background: var(--color-surface);
        border: 1px solid var(--color-border);
        border-radius: var(--radius-md);
        padding: 2.5rem 2.75rem;
        box-shadow: var(--shadow-md);
      }

      .cv-head h2 {
        margin: 0 0 var(--space-1);
        font-size: 1.6rem;
        color: var(--color-primary);
        letter-spacing: 0.01em;
      }

      .cv-contact {
        margin: 0;
        color: var(--color-text-secondary);
        font-size: var(--text-base);
        line-height: 1.5;

        .empty {
          color: var(--color-text-faint);
          font-style: italic;
        }
      }

      .cv-section {
        margin-top: var(--space-5);
        padding-top: var(--space-4);
        border-top: 1px solid var(--color-border);

        h3 {
          margin: 0 0 var(--space-3);
          font-size: var(--text-sm);
          text-transform: uppercase;
          letter-spacing: 0.06em;
          color: var(--color-accent);
        }
      }

      .cv-skills {
        display: flex;
        flex-wrap: wrap;
        gap: var(--space-2);
      }

      .skill-chip {
        padding: 0.15rem 0.6rem;
        border: 1px solid var(--color-border-strong);
        border-radius: var(--radius-full);
        font-size: var(--text-xs);
        color: var(--color-text-secondary);
      }

      .cv-entry {
        margin-bottom: var(--space-4);

        &:last-child {
          margin-bottom: 0;
        }
      }

      .cv-entry-head {
        display: flex;
        align-items: baseline;
        justify-content: space-between;
        gap: var(--space-3);
      }

      .cv-entry-sub {
        color: var(--color-text-secondary);
        font-size: var(--text-sm);
        margin-top: 1px;
      }

      .cv-dates {
        color: var(--color-text-muted);
        font-size: var(--text-xs);
        white-space: nowrap;
      }

      .cv-bullets {
        margin: var(--space-2) 0 0;
        padding-left: 1.1rem;
        color: var(--color-text);
        font-size: var(--text-sm);
        line-height: 1.5;
      }

      .cv-desc {
        margin: var(--space-1) 0 0;
        color: var(--color-text);
        font-size: var(--text-sm);
        line-height: 1.5;
      }

      @media (max-width: 768px) {
        :host {
          padding: var(--space-3);
        }
        .cv-preview-sheet {
          padding: var(--space-5);
        }
      }
    `,
  ],
})
export class CvPreviewComponent {
  readonly i18n = inject(I18nService);

  @Input({ required: true }) cv!: CVStructure;
  /** Display name for the resume header. */
  @Input() name = 'Your Name';

  formatDates(start: string | null, end: string | null): string {
    if (!start && !end) {
      return '—';
    }
    if (start && end) {
      return `${this.fmtMonth(start)} — ${this.fmtMonth(end)}`;
    }
    return this.fmtMonth(start || end || '');
  }

  private fmtMonth(value: string): string {
    const [year, month] = value.split('-');
    if (!year) {
      return value;
    }
    if (!month) {
      return year;
    }
    const idx = Number(month);
    const name = idx >= 1 && idx <= 12 ? this.i18n.t(`months.${idx}`) : month;
    return `${name} ${year}`;
  }
}

// mobile/src/components/cv-preview/CvPreview.tsx
import { StyleSheet, Text, View } from 'react-native';

import { useI18n } from '@/i18n/I18nProvider';
import { useTheme } from '@/theme/ThemeProvider';
import { CVStructure } from '@/types';
import { dateLocale, formatDateRange } from '@/utils/dates';

/**
 * Renders a CVStructure as a clean A4-style document — mirrors the web
 * `app-cv-preview` component used by the CV editor's Preview tab.
 */
export function CvPreview({ cv, name }: { cv: CVStructure; name: string }) {
  const { theme } = useTheme();
  const i18n = useI18n();
  const locale = dateLocale(i18n.lang);

  return (
    <View style={[styles.sheet, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}>
      <View style={styles.head}>
        <Text style={[styles.name, { color: theme.colors.primary }]}>{name}</Text>
        <Text style={[styles.summary, { color: theme.colors.textSecondary }]}>
          {cv.summary ? cv.summary : <Text style={[styles.empty, { color: theme.colors.textFaint }]}>{i18n.t('cvPreview.summaryEmpty')}</Text>}
        </Text>
      </View>

      {cv.skills.length > 0 ? (
        <Section title={i18n.t('cvPreview.skills')}>
          <View style={styles.skillsRow}>
            {cv.skills.map((skill) => (
              <View
                key={skill}
                style={[styles.skillChip, { borderColor: theme.colors.borderStrong }]}
              >
                <Text style={[styles.skillChipText, { color: theme.colors.textSecondary }]}>{skill}</Text>
              </View>
            ))}
          </View>
        </Section>
      ) : null}

      {cv.experience.length > 0 ? (
        <Section title={i18n.t('cvPreview.experience')}>
          {cv.experience.map((exp, index) => (
            <View key={index} style={styles.entry}>
              <View style={styles.entryHead}>
                <Text style={[styles.entryTitle, { color: theme.colors.text }]}>{exp.title}</Text>
                <Text style={[styles.dates, { color: theme.colors.textMuted }]}>
                  {formatDateRange(exp.start_date, exp.end_date, locale)}
                </Text>
              </View>
              <Text style={[styles.entrySub, { color: theme.colors.textSecondary }]}>{exp.company}</Text>
              {exp.bullets.length > 0 ? (
                <View style={styles.bullets}>
                  {exp.bullets.map((bullet, bulletIndex) => (
                    <Text key={bulletIndex} style={[styles.bullet, { color: theme.colors.text }]}>
                      •  {bullet}
                    </Text>
                  ))}
                </View>
              ) : null}
            </View>
          ))}
        </Section>
      ) : null}

      {cv.education.length > 0 ? (
        <Section title={i18n.t('cvPreview.education')}>
          {cv.education.map((edu, index) => (
            <View key={index} style={styles.entry}>
              <View style={styles.entryHead}>
                <Text style={[styles.entryTitle, { color: theme.colors.text }]}>{edu.degree}</Text>
                <Text style={[styles.dates, { color: theme.colors.textMuted }]}>{edu.year ?? ''}</Text>
              </View>
              <Text style={[styles.entrySub, { color: theme.colors.textSecondary }]}>{edu.institution}</Text>
            </View>
          ))}
        </Section>
      ) : null}

      {cv.projects.length > 0 ? (
        <Section title={i18n.t('cvPreview.projects')}>
          {cv.projects.map((project, index) => (
            <View key={index} style={styles.entry}>
              <View style={styles.entryHead}>
                <Text style={[styles.entryTitle, { color: theme.colors.text }]}>{project.name}</Text>
                {project.link ? <Text style={[styles.dates, { color: theme.colors.textMuted }]}>{project.link}</Text> : null}
              </View>
              {project.description ? (
                <Text style={[styles.projectDesc, { color: theme.colors.text }]}>{project.description}</Text>
              ) : null}
            </View>
          ))}
        </Section>
      ) : null}
    </View>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  const { theme } = useTheme();
  return (
    <View style={[styles.section, { borderTopColor: theme.colors.border }]}>
      <Text style={[styles.sectionTitle, { color: theme.colors.accent }]}>{title}</Text>
      <View style={styles.sectionBody}>{children}</View>
    </View>
  );
}

const styles = StyleSheet.create({
  sheet: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 24,
  },
  head: {
    marginBottom: 16,
  },
  name: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 6,
    letterSpacing: 0.2,
  },
  summary: {
    fontSize: 14,
    lineHeight: 20,
  },
  empty: {
    fontStyle: 'italic',
  },
  section: {
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  sectionBody: {
    gap: 12,
  },
  skillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  skillChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 9999,
    borderWidth: 1,
  },
  skillChipText: {
    fontSize: 12,
  },
  entry: {
    gap: 2,
  },
  entryHead: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 8,
  },
  entryTitle: {
    fontSize: 14,
    fontWeight: '700',
    flexShrink: 1,
  },
  entrySub: {
    fontSize: 13,
  },
  dates: {
    fontSize: 12,
  },
  bullets: {
    marginTop: 6,
    gap: 4,
  },
  bullet: {
    fontSize: 13,
    lineHeight: 19,
  },
  projectDesc: {
    fontSize: 13,
    lineHeight: 19,
    marginTop: 2,
  },
});
